### ISSUE TITLE
Error with python3.7

### ISSUE THREAD

**Issue by NameLessJedi** [c-soft/satel_integra#5] opened 2019-01-25 11:18 UTC
* Satel Integra version: 0.2.0
* Python version: 3.7.2 (python3.7_3.7.2-1_amd64.deb)
* Operating System: Debian Sid/Unstable

### Description
Debian Sid moved to python 3.7 as main python3 interpreter so I created fresh venv for HomeAssistant and installed from scratch.
During HA start there is: 

> hass[2286]: /home/hass/ha37/lib/python3.7/site-packages/satel_integra/satel_integra.py:327: RuntimeWarning: coroutine 'StreamReader.readuntil' was never awaited
> hass[2286]:   data = yield from self._reader.readuntil(b'\xFE\x0D')
> hass[2286]: RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> hass[2286]: 2019-01-25 09:51:29 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
> hass[2286]: Traceback (most recent call last):
> hass[2286]:   File "/home/hass/ha37/lib/python3.7/site-packages/satel_integra/satel_integra.py", line 398, in monitor_status
> hass[2286]:     yield from self.start_monitoring()
> hass[2286]:   File "/home/hass/ha37/lib/python3.7/site-packages/satel_integra/satel_integra.py", line 172, in start_monitoring
> hass[2286]:     resp = yield from self._read_data()
> hass[2286]:   File "/home/hass/ha37/lib/python3.7/site-packages/satel_integra/satel_integra.py", line 327, in _read_data
> hass[2286]:     data = yield from self._reader.readuntil(b'\xFE\x0D')
> hass[2286]: TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator

and the component is not working.

**Comment by NameLessJedi** [comment] 2019-02-14 11:10
Any ETA?
According to https://github.com/home-assistant/home-assistant/pull/20988 there can be some more ppl switching to python 3.7

**Comment by c-soft** [comment] 2019-02-15 23:01
I'm fixing some issues currently, so I hope to get it done too. Problem is I don't have environment with python 3.7 to reproduce the issue. Would you be willing to test it for me once I got fix attempt? 
Testing is about copying custom component to the config dir of HA.

**Comment by c-soft** [comment] 2019-02-16 17:10
I think I this issue, but it's not tested with Python 3.7.
Before new version is released officially you can test it out by copying contents of this zip:
https://www.dropbox.com/s/q3363q9lqofbiwk/satel_integra.zip?dl=0 

... to `config\homeassistant\components` directory.

Thanks!

**Comment by NameLessJedi** [comment] 2019-02-18 10:34
I've been away during weekend. Downloaded zip just now and will try it in the evening (I hope I did not remove python3.7 venv ;) )

**Comment by jfarcher** [comment] 2019-02-19 15:27
Building from docker file the install of dlib via pip fails. Looks like dlib won't compile on 3.7 yet.

**Comment by c-soft** [comment] 2019-02-19 20:08
What's dlib? 
can you share the logs please?

**Comment by jfarcher** [comment] 2019-02-19 20:16
Sorry ignore my previous comment, wrong project

**Comment by NameLessJedi** [comment] 2019-02-19 21:35
Works! :+1:  :) 
Tested also with python 3.6 venv and also no errors.
Will observe this for day or two before closing if that's ok with you :)
BTW this should be put in custom_components not components in HA config dir

**Comment by c-soft** [comment] 2019-02-20 08:25
Good to hear :)
Give it a good testing before closing :)

Regarding custom_components vs cumponents: if you put it in custom_components it won't work correctly (at least it didn't for me) because it will clash with already existing component within HA. 
Interesingly enough, it sorta worked for me but not quite this way.

**Comment by NameLessJedi** [comment] 2019-02-20 11:38
I've spoke too soon.
This morning I've spotted that it's unable to read state (armed/disarmed). It stays unknown :/

Somehow it won't work when put in component or components dir. Spits same error as before. Most probably because it downgrades satel_integra to 0.2.0. When I put it in custom_components it properly pulls satel_integra 0.3.2 :
lut 20 12:25:33 rhenvar hass[17318]: 2019-02-20 12:25:33 INFO (MainThread) [homeassistant.loader] Loaded satel_integra from custom_components.satel_integra
lut 20 12:25:33 rhenvar hass[17318]: 2019-02-20 12:25:33 WARNING (MainThread) [homeassistant.loader] You are using a custom component for satel_integra which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experien
lut 20 12:25:33 rhenvar hass[17318]: 2019-02-20 12:25:33 INFO (SyncWorker_6) [homeassistant.util.package] Attempting install of satel_integra==0.3.2
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [homeassistant.setup] Setting up satel_integra
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [homeassistant.setup] Setup of domain satel_integra took 0.0 seconds.
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [satel_integra.satel_integra] Starting monitor_status loop
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [satel_integra.satel_integra] Calling handler for id: 0x00
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [homeassistant.loader] Loaded alarm_control_panel.satel_integra from homeassistant.components.alarm_control_panel.satel_integra
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [satel_integra.satel_integra] Calling handler for id: 0x09
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [satel_integra.satel_integra] Calling handler for id: 0x0a
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [satel_integra.satel_integra] Calling handler for id: 0x0b
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [satel_integra.satel_integra] Calling handler for id: 0x10
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.satel_integra
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [satel_integra.satel_integra] Calling handler for id: 0x13
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [satel_integra.satel_integra] Calling handler for id: 0x17
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [satel_integra.satel_integra] Ignoring message: 0x1f
lut 20 12:25:38 rhenvar hass[17318]: 2019-02-20 12:25:38 INFO (MainThread) [satel_integra.satel_integra] Calling handler for id: 0x2a
lut 20 12:25:51 rhenvar hass[17318]: 2019-02-20 12:25:51 INFO (MainThread) [homeassistant.loader] Loaded binary_sensor.satel_integra from homeassistant.components.binary_sensor.satel_integra
lut 20 12:25:51 rhenvar hass[17318]: 2019-02-20 12:25:51 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.satel_integra
lut 20 12:25:58 rhenvar hass[17318]: 2019-02-20 12:25:58 INFO (MainThread) [satel_integra.satel_integra] Ignoring message: 0xee
lut 20 12:26:18 rhenvar hass[17318]: 2019-02-20 12:26:18 INFO (MainThread) [satel_integra.satel_integra] Ignoring message: 0xee

that last message repeats every 30s or so.

**Comment by nyxnyx** [comment] 2019-02-20 18:31
I had an error related to asyncio.coroutine.
Adding one line to satel_integra.py (an HA component file) helped to fix it:
```
  325     @asyncio.coroutine
  326     def _read_data(self):

```

**Comment by NameLessJedi** [comment] 2019-02-20 22:09
@c-soft that component vs custom_components might be related to HA version? I'm on 0.86.2 and while browsing announcement about 0.88 I've spotted some changes around custom components. I'll wait a bit for 0.88.1+ and will update
Just to make sure by config\homeassistant you mean config dir, right? The place where configuration.yaml is.
@nyxnyx  With this change to 0.2.0 it runs w/o errors with python 3.7 and properly detects alarm state, but this won't work with 0.3.2 as it's rewritten to use async.

**Comment by nyxnyx** [comment] 2019-02-21 06:12
@NameLessJedi currently I have only version 0.2.0. My problem was with errors under python 3.7 - now they gone. If I have time - I will try to upgrade to 0.3.2 and see what is going on.
@c-soft thank you for your effort!

**Comment by c-soft** [comment] 2019-02-21 08:11
can you attach full log on a debug level? 
Please remember to turn on debug for both the library (as you already have) and HA component.

**Comment by NameLessJedi** [comment] 2019-02-22 23:25
I've been trying to pinpoint just the satel component debug but so far I failed. Can you help with proper logger: config? I've even tried to put homeassistant.components: debug but this doesn't seem to affect Satel

**Comment by c-soft** [comment] 2019-02-28 18:58
@NameLessJedi what version of HA do you have? 
I found it only works if you have at least 0.88, and put the component into ./config/custom_components. 
With previous versions it only loads __init__.py  and you actually would see this issue. 

Now for the proper logging config:

```
logger:
  default: warning
  logs:
    homeassistant.components.satel_integra: debug
    custom_components.satel_integra: debug
     satel_integra.satel_integra: debug
```

**Comment by NameLessJedi** [comment] 2019-03-06 21:11
At first I tested with 0.86. I've just upgraded to 0.88.2 and so far seems to work OK. HA got proper arm state (disarmed at the moment).

Sorry for delay but I had really rough last two weeks.

**Comment by NameLessJedi** [comment] 2019-03-07 11:01
@c-soft I've tested it some more and still no errors. Motion sensors work smoothly, (dis)arming also,
From my point of view this is ready to go :)
I'm using your zip from Feb, 16th

**Comment by c-soft** [comment] 2019-03-07 22:43
Happy to hear that! The good news is that code has been accepted to the official HA codebase now so it will be available with the next release. I will close the issue then.

**Comment by sickidolderivative** [comment] 2019-03-08 06:36
Hi c-soft

I copied the dropbox files to /config/custom_components and got the following errors:

`2019-03-08 07:27:37 ERROR (MainThread) [homeassistant.config] Invalid config for [satel_integra]: required key not provided @ data['satel_integra']['code']. Got None. (See /config/configuration.yaml, line 197). Please check the docs at https://home-assistant.io/components/satel_integra/
2019-03-08 07:27:37 ERROR (MainThread) [homeassistant.setup] Setup failed for satel_integra: Invalid config.`

My satel_integra config is the following:
`satel_integra:
  host: x.x.x.x
  port: 7094
  partition: 1
  arm_home_mode: 1
  zones:
    01:
      name: "Salon"
      type: "motion"`

I'm running Hassio 0.89.0 on HassOS 2.10. Does that make any sense?

**Comment by c-soft** [comment] 2019-03-08 07:26
Huh, of you have no „switchable_outputs” defined, it should not force you to put in  code.
Enter some random code as a workaround, I will look into it.

**Comment by sickidolderivative** [comment] 2019-03-08 08:21
Yay! It works! Thanks for the hint and for maintaining the project. I would eagerly buy you a coffee for your work.

**Comment by c-soft** [comment] 2019-03-08 09:09
Great to hear that it works and thank you for kind words! In the meantime I will verify the config check issue, so it works when it's official.

**Comment by c-soft** [comment] 2019-03-08 17:17
I'm going to close this ticket now as it should be fixed in the next HA release.
@NameLessJedi If the python 3.7 problem reoccurs, please feel free to reopen. 
@sickidolderivative the issue you have found is unrelated to this bug. I have also failed to reproduce what you have observed, but if you will see same weird behavior in next official or unofficial release I make - please enter new bug. Thanks everyone!

**Closed by c-soft** 2019-03-08 17:17 UTC
